services:
  - type: web
    name: pizzaria-da-livia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /api/health
    initialDeployHooks:
      - command: sleep 10 # Wait for database to be ready
    healthCheckTimeout: 300
    dependencies:
      - name: pizzaria-db

databases:
  - name: pizzaria-db
    databaseName: pizzaria_livia
    ipAllowList: []
    plan: free 