services:
  - type: web
    name: pizzaria-da-livia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        fromService:
          type: mongodb
          name: pizzaria-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /api/health
    healthCheckTimeout: 300

databases:
  - type: mongodb
    name: pizzaria-db
    databaseName: pizzaria_livia
    ipAllowList: []
    plan: free 