services:
  - type: web
    name: pizzaria-da-livia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false # Permite que o valor seja definido manualmente no dashboard
    autoDeploy: true
    healthCheckPath: /api/health
    healthCheckTimeout: 300

databases:
  - name: pizzaria-mongodb
    databaseName: pizzaria
    plan: free
    postDeploy:
      - echo "MongoDB database deployed!" 