services:
  - type: web
    name: pizzaria-da-livia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /api/health
    healthCheckTimeout: 300

  - type: mongodb
    name: pizzaria-db
    plan: free
    ipAllowList: []
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI} 